# Generated by Django 5.0.3 on 2024-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App', '0002_movie_lib'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=200)),
                ('doc', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
