# Generated by Django 5.0.3 on 2024-03-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=50)),
                ('Release_year', models.IntegerField()),
            ],
        ),
    ]
