# Generated by Django 5.0.3 on 2024-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Lib_ID', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Name',
            new_name='Title',
        ),
    ]
